# Copyright (C) 2025 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

name: CI SEAPATH yocto image builder

on:
 workflow_dispatch:

permissions:
  actions: write
  checks: write

jobs:
  CI:
    runs-on: [seapath-yocto-builder]
    steps:
      - name: Configure runner - Install repo
        run:
          apt update;
          curl -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo;
          chmod +x /usr/local/bin/repo;
      - name: Configure runner - Install cqfd
        run:
          apt-get -y install bash-completion build-essential git;
          git clone https://github.com/savoirfairelinux/cqfd.git;
          cd cqfd;
          make install;
      - name: Initialize sources
        run:
          git config --global user.email "seapath@seapath.com";
          git config --global user.name "seapath-ci";
          git config --global color.ui false;
          cd ..;
          mkdir build;
          cd build;
          repo init -u https://github.com/seapath/repo-manifest.git;
          repo sync;
          cqfd init;
